config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  resources :items
  resources :categories
  resources :collections
  resources :users
  #get 'home/index'
  get 'home/about'
  root 'home#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :user
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  # GET /collections or /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1 or /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy!

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:name, :description, :category, :image_url, :user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div class="container">
  <div id="<%= dom_id collection %>" class="card">
    <div class="card-body">
      <h5 class="card-title"><strong><%= collection.name %></strong></h5>

      <img src="<%= collection.image_url %>" class="card-img-top" alt="Collection Image" width="200" height="200">

      <div class="mb-3">
        <strong>Description:</strong>
        <%= collection.description %>
      </div>

      <div class="mb-3">
        <strong>Category:</strong>
        <%= collection.category %>
      </div>

      <div class="mb-3">
        <strong>Image URL:</strong>
        <%= collection.image_url %>
      </div>

      <div class="mb-3">
        <strong>Total no. of items:</strong> 
        <%= collection.items.count %>
      </div>

      <div class="mb-3">
        <strong>List of all items:</strong>
        <ul>
          <% collection.items.each do |item| %>
            <li>
              <strong>Name:</strong> <%= item.name %> </br>
              <strong>Description:</strong> <%= item.description %> </br>
              <strong>Image URL:</strong> <%= item.image_url %> </br>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="mb-3">
        <strong>Collection author:</strong>
        <%= collection.user.nickname %> 
      </div>
    </div>
  </div>
</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection, class: "needs-validation", novalidate: true) do |form| %>
  <% if collection.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :category_id, class: "form-label" %>
    <%= form.collection_select :category, Category.all, :name, :name, {}, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :image_url, class: "form-label" %>
    <%= form.text_field :image_url, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :user_id, class: "form-label" %>
    <%= form.collection_select :user_id, User.all, :id, :email, {}, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Show this collection", @collection, class:"btn btn-success" %> |
  <%= link_to "Back to collections", collections_path, class:"btn btn-secondary" %>
</div>

app/views/collections/index.html.erb
<h1 class="mt-4 mb-3">My collections</h1>

<div id="collections" class="row">
  <% @collections.each do |collection| %>
    <div class="col-md-4 mb-3">
      <%= render collection, class: "card" %>
      <p class="mt-2">
        <%= link_to "Show this collection", collection, class: "btn btn-secondary" %>
      </p>
      <%= link_to "New collection", new_collection_path, class: "btn btn-success mt-3" %>
    </div>
  <% end %>
</div>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Back to collections", collections_path, class:"btn btn-dark" %>
</div>

app/views/collections/show.html.erb
<%= render @collection %>
</br>
<div>
  <%= link_to "Edit this collection", edit_collection_path(@collection), class:"btn btn-success" %> |
  <%= link_to "Back to collections", collections_path, class:"btn btn-secondary" %>
  </br> </br>
  <%= button_to "Delete", @collection, method: :delete, class:"btn btn-danger" %>
</div>