config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  resources :items
  resources :categories
  resources :collections
  resources :users
  #get 'home/index'
  get 'home/about'
  root 'home#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @top_collections = Collection
                         .select('collections.*, COUNT(items.id) as items_count')
                         .joins(:items)
                         .group('collections.id')
                         .order('items_count DESC')
                         .limit(3)
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-success">
  <div class="container-fluid">
  	<%= link_to 'MyCollection', root_path, class:"navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to 'My collections', collections_path, class:"nav-link text-light" %>
        <%= link_to 'Add collection', new_collection_path, class:"nav-link text-light" %>
        <%= link_to 'About us', home_about_path, class:"nav-link text-light" %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Type your tags here..." aria-label="Search">
        <button class="btn btn-outline-dark me-2 text-white" type="submit">Search</button>
      </form>
      <div class="d-flex">
      <%= link_to "Sign up", new_user_registration_path, class:"btn btn-primary me-2" %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"btn btn-dark me-2" %>
      <%= link_to "Log in", new_user_session_path, class:"btn btn-primary text-white" %>
      </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container my-5">
  <div class="card shadow-lg">
    <div class="card-header bg-success text-white">
      <h1 class="card-title mb-0">About Us</h1>
    </div>
    <div class="card-body">
      <h3 class="card-subtitle mb-3">Est. in 2024</h3>
      <p class="card-text">
        This is my first Ruby on Rails web-application. The application provides users with the ability to manage and store their collections, which are divided by categories.
      </p>
      <p class="card-text">
        For any inquiries, feel free to reach out to me:
      </p>
      <h4>
        <i class="fas fa-envelope"></i> <a href="mailto:marsul607@gmail.com">marsul607@gmail.com</a>
      </h4>
    </div>
    <div class="card-footer text-muted">
      Thank you for visit!
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1 class="mt-4 mb-3">Top Collections</h1>

<% if @top_collections.present? %>
  <% @top_collections.each_with_index do |collection, index| %>
    <div class="col-md-4 mb-3">
      <%= render collection, class: "card" %>
      <p class="mt-2">
        <%= link_to "Show this collection", collection, class: "btn btn-secondary" %>
      </p>
      <%= link_to "New collection", new_collection_path, class: "btn btn-success mt-3" %>
    </div>
  <% end %>
<% else %>
  <p>No top collections found.</p>
<% end %>